title: Campus Clubhouse
description: Central hub for student run clubs at UH Manoa.
google_analytics:
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: true
  repository_url: https://github.com/campus-clubhouse/campus-clubhouse
  document_url: https://github.com/campus-clubhouse/campus-clubhouse.github.io
gems:
  - jekyll-mentions
